export const API_URL = 'https://amanuelasfaw.pythonanywhere.com';
// export const API_URL = 'http://127.0.0.1:8000';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';

export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';

export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';

export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';

export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

export const CART_RESET_ITEMS = 'CART_RESET_ITEMS';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';

export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';

export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';

export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';

export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';

export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';

export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';

export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';

export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
